sudo: required
services:
  - docker
before_install:
  - docker build -t psinthorn/f2-frontend -f Dockerfile.dev . 

script: 
  - docker run psinthorn/f2-frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "f2-frontend"
  env: "F2Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-531876997458"
  bucket_path: "f2-frontend"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
